#!/usr/bin/env bash
# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Start Nginx service
sudo service nginx start

# Enable Nginx to start on boot
sudo service nginx enable

# Create or overwrite index.html with "HELLO WORLD!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Check Nginx service status
sudo service nginx status

