#!/usr/bin/env bash
#In this first task you need to configure web-02 to be identical

redirect_string='return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;'

sudo sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\t'"$redirect_string"'\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
