#!/usr/bin/env bash
# configure a load-balancing server

# Install necessary tools
sudo apt-get update -y
sudo apt-get install -y --no-install-recommends software-properties-common

# Add HAproxy PPA and install specific version of HAproxy
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update -y
sudo apt-get install -y haproxy=2.4.*

# Configure HAproxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg <<EOF
global
	log /dev/log local0
	log /dev/log local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log global
	mode http
	option httplog
	option dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http

frontend localnodes
	bind *:80
	mode http
	default_backend nodes

backend nodes
	mode http
	balance roundrobin
	server 350788-web-01 3.94.185.199:80 check
	server 350788-web-02 35.153.51.84:80 check
EOF'

# Restart HAproxy to apply the new configuration
sudo service haproxy restart

# Enable HAproxy to start on boot
sudo systemctl enable haproxy
