#!/usr/bin/env bash

# Install necessary tools
sudo apt-get update -y
sudo apt-get install -y --no-install-recommends software-properties-common

# Add HAproxy PPA and install a specific version of HAproxy
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update -y
sudo apt-get install -y haproxy=2.4.*

# Configure HAproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
	log /dev/log local0
	log /dev/log local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log global
	mode http
	option httplog
	option dontlognull
	option http-server-close
	option forwardfor
	option redispatch
	retries 3
	timeout http-request 10s
	timeout queue 1m
	timeout connect 10s
	timeout client 1m
	timeout server 1m
	timeout http-keep-alive 10s
	timeout check 10s
	maxconn 3000

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server 350788-web-01 3.94.185.199:80 check
	server 350788-web-02 35.153.51.84:80 check
EOF

# Restart HAproxy to apply the new configuration
sudo systemctl restart haproxy

# Enable HAproxy to start on boot
sudo systemctl enable haproxy

# Ensure the hostname is correctly set for lb-01
sudo hostnamectl set-hostname lb-01

# Verify HAproxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Check the status of HAproxy to ensure it is running
sudo systemctl status haproxy
