#!/usr/bin/env bash
#this prints a text 9 times using a while-loop and an if loop and then display another message

i="1"
while [ $i -le 9 ]
do
	echo "Best School"
	i=$((i+1))
done

if [ $i -eq 10 ]; then
	echo "Hi"
fi
echo "Best School"
