#!/usr/bin/env bash
# This script prints 10 messages, using a while loop, if, elif, and else

i="1"
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 4 ]; then
	    echo "bad luck"
elif [ $i -eq 8 ]; then
	echo "good luck"
else
	echo "No special luck"
    fi
    i=$((i+1))
done
