#!/usr/bin/env bash
# Install UFW
sudo apt update
sudo apt install -y ufw

# Enable IPv6
sudo sed -i 's/IPV6=no/IPV6=yes/' /etc/default/ufw

# Set default incoming policy to deny
sudo ufw default deny incoming

# Allow outgoing by default
sudo ufw default allow outgoing

# Allow specific ports
sudo ufw allow 22/tcp   # SSH
sudo ufw allow 443/tcp  # HTTPS
sudo ufw allow 80/tcp   # HTTP

# Enable UFW and show added rules
sudo ufw enable
sudo ufw status verbose
