#!/usr/bin/env bash
#this script changes my IP Address

new_local_ip="127.0.0.2"
new_facebook_ip="8.8.8.8"  
hosts_file="/etc/hosts"

sed -i "s/^127.0.0.1.*$/127.0.0.1\tlocalhost\n$new_local_ip\tnewhost/g" "$hosts_file"
sed -i "s/^facebook.com.*$/new_facebook_ip\tfacebook.com/g" "$hosts_file"
