#!/usr/bin/env bash
# Write a Bash script that configures the container to fit the above requirements

#sudo adduser nginx
sudo sed -i "s/listen 80 default_server;/listen 8080 default_server;/" /etc/nginx/sites-available/default
sudo sed -i "s/listen [::]:80 default_server;/listen [::]:8080 default_server;/" /etc/nginx/sites-available/default
sudo sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo service nginx restart
